version: '2'
networks:
  web:
    external: true
services:
  devsetgo:
    build: ./
    image: mikeryan56/7oi:latest
    container_name: "sevenofi"
    restart: always
    ports:
    - "80"
    volumes:
    - .:/code
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.7oi.rule=Host(`sevenofi.com`)"
    - "traefik.http.routers.7oi.entrypoints=websecure"
    - "traefik.http.routers.7oi.tls.certresolver=mytlschallenge"

    networks:
      - web